/* global tf */
/* eslint-disable import/extensions */
import {
  button,
  dashboard,
  parameters,
  progress,
  slider,
  text,
  webcam,
} from '../../dist/marcelle.bundle.esm.js';
import { displaySamples, displayTensor } from './visualization.js';
// import { GanTrainer, plotGanTraining } from './training.js';
import { GanTrainer, plotGanTraining } from './training_emulator.js';
import { loadModel, predict, generateNoise, downsampleCamera } from './generation.js';

// Create a GAN model trainer, that communicates with a Python training backend
const gan = new GanTrainer({ epochs: 30000 });

// --------------------------------
// TRAINING
// --------------------------------
const [plotLosses, plotAccuracy] = plotGanTraining(gan);

const trainingLauncher = button({ text: 'Start Training' });
trainingLauncher.title = 'Training Launcher';
gan.$training
  .map((x) => x.status)
  .skipRepeats()
  .subscribe((x) => {
    if (['start', 'epoch'].includes(x)) {
      trainingLauncher.$text.set('Stop Training');
    } else {
      trainingLauncher.$text.set('Start Training');
    }
  });
trainingLauncher.$click.subscribe(() => {
  if (['start', 'epoch'].includes(gan.$training.value.status)) {
    gan.stop();
  } else {
    gan.train();
  }
});

// Display samples generated by the GAN along the training process
const samples = displaySamples(gan);

// --------------------------------
// GENERATION
// --------------------------------
const genButton = button({ text: 'Generate an Image' });
const $imagesOneShot = genButton.$click.thru(generateNoise).thru(predict);

const w = webcam({ width: 10, height: 10 });
const $webcamNoise = w.$images.filter(() => w.$ready.value).thru(downsampleCamera);
const $imagesWebcam = $webcamNoise
  .map((input) => input.sub(tf.scalar(0.5).mul(tf.scalar(2))).reshape([1, 100]))
  .thru(predict);

const displayInput = displayTensor($webcamNoise, 'Input Noise');

const displayResult = displayTensor($imagesOneShot.merge($imagesWebcam), 'Generated Image');

const modelSlider = slider({
  step: 1,
  pips: true,
  pipstep: 1,
  formatter: (i) => {
    if (gan.$models.value[i]) {
      return `${gan.$models.value[i].split('generator_')[1].split('.h5')[0]}`;
    }
    return '0';
  },
});
modelSlider.title = 'Browse Model Training History (Ticks indicate the number of epochs)';
gan.$models.subscribe((x) => {
  modelSlider.$max.set(Math.max(1, x.length - 1));
});

const loadButton = button({ text: 'Load Model' });
loadButton.title = 'Load model';
loadButton.$click.subscribe(async () => {
  loadButton.$loading.set(true);
  await loadModel(gan.$models.value[modelSlider.$values.value[0]]);
  loadButton.$loading.set(false);
});

const arrow = text({
  text:
    '<div style="flex-grow: 1; align-self: center; text-align: center; font-size: 4rem;">⇨</div>',
});

const dash = dashboard({
  title: 'Marcelle Example - GAN for Image Generation (MNIST)',
  author: 'Marcelle Pirates Crew',
});

dash
  .page('Train')
  .useLeft(parameters(gan), trainingLauncher)
  .use(progress(gan), samples, [plotLosses, plotAccuracy]);
dash.page('Simple').use(modelSlider, [loadButton, genButton], displayResult);
dash
  .page('Webcam')
  .useLeft(w)
  .use(text({ text: 'Love on the beat' }), modelSlider, loadButton, [
    displayInput,
    arrow,
    displayResult,
  ]);

dash.start();
